services:
  postgres:
    image: postgres:17
    container_name: lifeof_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - lifeof_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: lifeof_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - lifeof_redis_data:/data

volumes:
  lifeof_postgres_data:
  lifeof_redis_data:
